// AutolinkedNativeModules.g.cpp contents generated by "react-native autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @dr.pogodin/react-native-static-server
#include <winrt/ReactNativeStaticServer.h>

// Includes from @dr.pogodin/react-native-fs
#include <winrt/ReactNativeFs.h>

// Includes from react-native-webview
#include <winrt/ReactNativeWebView.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @dr.pogodin/react-native-static-server
    packageProviders.Append(winrt::ReactNativeStaticServer::ReactPackageProvider());
    // IReactPackageProviders from @dr.pogodin/react-native-fs
    packageProviders.Append(winrt::ReactNativeFs::ReactPackageProvider());
    // IReactPackageProviders from react-native-webview
    packageProviders.Append(winrt::ReactNativeWebView::ReactPackageProvider());
}

}
